### ISSUE TITLE
Server error with 1.0.7 and 1.3.1 of bukkit

### ISSUE THREAD

**Issue by Corosar** [orion304/MinecraftTLA#21]
when trying to load up version 1.3.1 of bukkit with version 1.0.7 of minecraftTLA i recieve this error log 

[INFO] Starting minecraft server version 1.3.1
2012-08-14 01:53:44 [INFO] Loading properties
2012-08-14 01:53:44 [INFO] Default game type: SURVIVAL
2012-08-14 01:53:44 [INFO] Generating keypair
2012-08-14 01:53:45 [INFO] Starting Minecraft server on *:25566
2012-08-14 01:53:45 [INFO] This server is running CraftBukkit version git-Bukkit-1.3.1-R1.0-b2320jnks (MC: 1.3.1) (Implementing API version 1.3.1-R1.0)
2012-08-14 01:53:45 [SEVERE] Could not load 'plugins\MinecraftTLA_v1.0.7(1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: main/Bending : Unsupported major.minor version 51.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:155)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:222)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:198)
    at net.minecraft.server.ServerConfigurationManagerAbstract.<init>(ServerConfigurationManagerAbstract.java:50)
    at net.minecraft.server.ServerConfigurationManager.<init>(SourceFile:11)
    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:105)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:380)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.UnsupportedClassVersionError: main/Bending : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144)
    ... 9 more
2012-08-14 01:53:45 [INFO] Preparing level "world"
2012-08-14 01:53:46 [INFO] Preparing start region for level 0 (Seed: 4057898428533182488)
2012-08-14 01:53:47 [INFO] Preparing spawn area: 89%
2012-08-14 01:53:47 [INFO] Preparing start region for level 1 (Seed: 4057898428533182488)
2012-08-14 01:53:48 [INFO] Preparing spawn area: 52%
2012-08-14 01:53:48 [INFO] Preparing start region for level 2 (Seed: 4057898428533182488)
2012-08-14 01:53:49 [INFO] Preparing spawn area: 36%
2012-08-14 01:53:49 [INFO] Server permissions file permissions.yml is empty, ignoring it
2012-08-14 01:53:50 [INFO] Done (4.126s)! For help, type "help" or "?"

any idea to fix it on my side me and my friends are having fun with 1.0.6 (which works with the 1.3.1 bukkit) or did i just download it from the wrong place (Which i used the download link from the Wiki). 

It would be nice to hear back on this but if you can't get back in time i will understand i have no clue how to code in java and frankly it confuses me a little. thanks for taking the time to address this.

**Comment by MistPhizzle** [comment]
Your JRE is out of date. Update and then change your startup script to include jre7 instead of jre6. :)

**Comment by Corosar** [comment]
thanks for coming to my aid quickly
