### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by HiddenCloud** [orion304/MinecraftTLA#24]
Everytime I start the server and like check the console after a few minutes (with players online who play and bend) I keep getting this.

02:36:14 PM
 CONSOLE:
[SEVERE] java.lang.NullPointerException: Nodes must be provided.
02:36:15 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:29)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:171)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:201)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:96)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:66)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:261)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:233)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dump(Yaml.java:209)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:54)
02:36:15 PM
 CONSOLE:
[SEVERE] at main.BendingPlayers.save(BendingPlayers.java:79)
02:36:15 PM
 CONSOLE:
[SEVERE] at main.BendingPlayers.setKey(BendingPlayers.java:52)
02:36:15 PM
 CONSOLE:
[SEVERE] at main.StorageManager.removeAbility(StorageManager.java:868)
02:36:15 PM
 CONSOLE:
[SEVERE] at main.StorageManager.removeBending(StorageManager.java:70)
02:36:15 PM
 CONSOLE:
[SEVERE] at main.PlayerStorageWriter$Task.call(PlayerStorageWriter.java:171)
02:36:15 PM
 CONSOLE:
[SEVERE] at main.PlayerStorageWriter.run(PlayerStorageWriter.java:218)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
02:36:15 PM
 CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
02:36:15 PM
 CONSOLE:
[SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
02:36:15 PM
 CONSOLE:
[SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
02:36:15 PM
 CONSOLE:
[SEVERE] at java.lang.Thread.run(Unknown Source)
02:36:15 PM
 *Blast:
[Member] shockingscream> .-.
02:36:18 PM
 CONSOLE:
[SEVERE] java.util.ConcurrentModificationException
02:36:18 PM
 CONSOLE:
[SEVERE] at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
02:36:18 PM
 CONSOLE:
[SEVERE] at java.util.ArrayList$Itr.next(Unknown Source)
02:36:18 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:142)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:146)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:108)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:271)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:261)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:233)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dump(Yaml.java:209)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:54)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.BendingPlayers.save(BendingPlayers.java:79)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.BendingPlayers.setKey(BendingPlayers.java:52)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.StorageManager.removeAbility(StorageManager.java:868)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.StorageManager.removeBending(StorageManager.java:70)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.PlayerStorageWriter$Task.call(PlayerStorageWriter.java:171)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.PlayerStorageWriter.run(PlayerStorageWriter.java:218)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
02:36:19 PM
 CONSOLE:
[SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
02:36:19 PM
 CONSOLE:
[SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
02:36:19 PM
 CONSOLE:
[SEVERE] at java.lang.Thread.run(Unknown Source)
02:36:19 PM
 CONSOLE:
[SEVERE] java.lang.NullPointerException: Nodes must be provided.
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:29)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:171)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:201)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:96)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:66)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:261)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:233)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dump(Yaml.java:209)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:54)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.BendingPlayers.save(BendingPlayers.java:79)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.BendingPlayers.setKey(BendingPlayers.java:52)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.StorageManager.removeAbility(StorageManager.java:868)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.StorageManager.removeBending(StorageManager.java:70)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.PlayerStorageWriter$Task.call(PlayerStorageWriter.java:171)
02:36:19 PM
 CONSOLE:
[SEVERE] at main.PlayerStorageWriter.run(PlayerStorageWriter.java:218)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
02:36:19 PM
 CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
02:36:19 PM
 CONSOLE:
[SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
02:36:19 PM
 CONSOLE:
[SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
02:36:19 PM
 CONSOLE:
[SEVERE] at java.lang.Thread.run(Unknown Source)
02:36:19 PM
 PLAYER_COMMAND:
Tha_Thunder: /f who thekillers
02:36:21 PM
 CONSOLE:
[INFO] shockingscream issued server command: /b d fire
02:36:22 PM
 CONSOLE:
[INFO] essentialz issued server command: /b b heatcontrol
02:36:24 PM
 CONSOLE:
[INFO] essentialz issued server command: /b choose fire
02:36:27 PM
 CONSOLE:
[INFO] essentialz issued server command: /b b heatcontrol
02:36:28 PM
 Buycraft:
Package checker successfully executed.
02:36:28 PM
 *Blast:
[Member] shockingscream> OW
02:36:34 PM
 CONSOLE:
[SEVERE] java.lang.NullPointerException: Nodes must be provided.
02:36:35 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:29)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:171)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:201)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:96)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:66)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:261)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:233)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.yaml.snakeyaml.Yaml.dump(Yaml.java:209)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:54)
02:36:35 PM
 CONSOLE:
[SEVERE] at main.BendingPlayers.save(BendingPlayers.java:79)
02:36:35 PM
 CONSOLE:
[SEVERE] at main.BendingPlayers.setKey(BendingPlayers.java:52)
02:36:35 PM
 CONSOLE:
[SEVERE] at main.StorageManager.removeAbility(StorageManager.java:868)
02:36:35 PM
 CONSOLE:
[SEVERE] at main.StorageManager.removeBending(StorageManager.java:70)
02:36:35 PM
 CONSOLE:
[SEVERE] at main.PlayerStorageWriter$Task.call(PlayerStorageWriter.java:171)
02:36:35 PM
 CONSOLE:
[SEVERE] at main.PlayerStorageWriter.run(PlayerStorageWriter.java:218)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
02:36:35 PM
 CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
02:36:35 PM
 CONSOLE:
[SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
02:36:35 PM
 CONSOLE:
[SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
02:36:35 PM
 CONSOLE:
[SEVERE] at java.lang.Thread.run(Unknown Source)

And then a few minutes later it starts again and it's really annoying. Maybe you could find a fix for it, I tried my best to fix it myself but I didn't make this plugin so I don't know everything about how it works.

It also fills up the whole console (McMyAdmin).

**Comment by HiddenCloud** [comment]
Alright, this time I managed to completely fix it. At bendingPlayers.java at the setkey line next to the if(!(bendingPlayers != null)) add && key != null && field != null). That should take care of it. When I commited I had made multiple updates so I can't make a pull request, but I hope this helps some other people.
